spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
server.port: 9000
management.endpoints.web.exposure.include: "*"
