server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Pandey12345@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
services:
  user: http://localhost:8081
  course: http://localhost:8082
  classroom: http://localhost:8083
  assessment: http://localhost:8084
  notification: http://localhost:8085
