spring:
  application:
    name: assessment-service
  datasource:
    url: jdbc:mysql://localhost:3306/assessmentdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084
