spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
  config.import: optional:configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
server.port: 0
management.endpoints.web.exposure.include: "*"
